"""Resolver-owned error types."""

from aptitude.domain.errors.resolver_errors import (
    AptitudeResolverError,
    ContentChecksumMismatchError,
    DependencyCycleError,
    DiscoveryNoCandidatesError,
    InteractiveSelectionUnavailableError,
    InvalidResolverConfigurationError,
    InvalidCoordinateError,
    InvalidLockfileError,
    PolicyViolationError,
    RegistryAccessError,
    RegistryUnavailableError,
    SelectionSlugNotFoundError,
    SkillNotFoundError,
    SkillSelectionError,
    UnsupportedDependencyShapeError,
    UnexpectedRegistryResponseError,
    VersionConflictError,
)

__all__ = [
    "AptitudeResolverError",
    "ContentChecksumMismatchError",
    "DependencyCycleError",
    "DiscoveryNoCandidatesError",
    "InteractiveSelectionUnavailableError",
    "InvalidResolverConfigurationError",
    "InvalidCoordinateError",
    "InvalidLockfileError",
    "PolicyViolationError",
    "RegistryAccessError",
    "RegistryUnavailableError",
    "SelectionSlugNotFoundError",
    "SkillNotFoundError",
    "SkillSelectionError",
    "UnsupportedDependencyShapeError",
    "UnexpectedRegistryResponseError",
    "VersionConflictError",
]
